namespace SalesApiStub.Models;

/// <summary>
/// Response payload returned after an order is successfully created.
/// </summary>
public class OrderResponse
{
    /// <summary>Unique order ID generated by the API.</summary>
    public Guid OrderId { get; set; }

    /// <summary>Shipping address for the order.</summary>
    public int ShippingAddressId { get; set; }

    /// <summary>ISO currency code shared by all order line prices.</summary>
    public string Currency { get; set; } = "EUR";

    /// <summary>Total amount before taxes.</summary>
    public decimal Subtotal { get; set; }

    /// <summary>Tax amount calculated by the stub.</summary>
    public decimal Tax { get; set; }

    /// <summary>Total amount including taxes.</summary>
    public decimal Total { get; set; }

    /// <summary>The UTC timestamp when the order was created.</summary>
    public DateTime CreatedAtUtc { get; set; }

    /// <summary>The list of lines included in the order.</summary>
    public List<OrderLineResponse> Items { get; set; } = [];
}
